export const PERSONS = {
'Luke Skywalker' : 'https://vignette.wikia.nocookie.net/starwars/images/2/20/LukeTLJ.jpg',
'C-3PO' : 'https://vignette.wikia.nocookie.net/starwars/images/3/3f/C-3PO_TLJ_Card_Trader_Award_Card.png',
'R2-D2' : 'https://vignette.wikia.nocookie.net/starwars/images/e/eb/ArtooTFA2-Fathead.png',
'Darth Vader' : 'https://vignette.wikia.nocookie.net/fr.starwars/images/3/32/Dark_Vador.jpg',
'Leia Organa' : 'https://vignette.wikia.nocookie.net/starwars/images/f/fc/Leia_Organa_TLJ.png',
'Owen Lars' : 'https://vignette.wikia.nocookie.net/starwars/images/e/eb/OwenCardTrader.png',
'Beru Whitesun lars' : 'https://vignette.wikia.nocookie.net/starwars/images/c/cc/BeruCardTrader.png',
'R5-D4' : 'https://vignette.wikia.nocookie.net/starwars/images/c/cb/R5-D4_Sideshow.png',
'Biggs Darklighter' : 'https://vignette.wikia.nocookie.net/starwars/images/0/00/BiggsHS-ANH.png',
'Obi-Wan Kenobi' : 'https://vignette.wikia.nocookie.net/starwars/images/4/4e/ObiWanHS-SWE.jpg',
'Anakin Skywalker' : 'https://vignette.wikia.nocookie.net/starwars/images/6/6f/Anakin_Skywalker_RotS.png',
'Wilhuff Tarkin' : 'https://vignette.wikia.nocookie.net/starwars/images/c/c1/Tarkininfobox.jpg',
'Chewbacca' : 'https://vignette.wikia.nocookie.net/starwars/images/4/48/Chewbacca_TLJ.png',
'Han Solo' : 'https://vignette.wikia.nocookie.net/starwars/images/e/e2/TFAHanSolo.png',
'Greedo' : 'https://vignette.wikia.nocookie.net/starwars/images/c/c6/Greedo.jpg',
'Jabba Desilijic Tiure' : 'https://vignette.wikia.nocookie.net/starwars/images/7/7f/Jabba_SWSB.png',
'Wedge Antilles' : 'https://vignette.wikia.nocookie.net/starwars/images/6/60/WedgeHelmetless-ROTJHD.jpg',
'Jek Tono Porkins' : 'https://vignette.wikia.nocookie.net/starwars/images/e/eb/JekPorkins-DB.png',
'Yoda' : 'https://vignette.wikia.nocookie.net/starwars/images/d/d6/Yoda_SWSB.png',
'Palpatine' : 'https://vignette.wikia.nocookie.net/starwars/images/d/d8/Emperor_Sidious.png',
'Boba Fett' : 'https://vignette.wikia.nocookie.net/starwars/images/7/79/Boba_Fett_HS_Fathead.png',
'IG-88' : 'https://vignette.wikia.nocookie.net/starwars/images/f/f2/IG-88.png',
'Bossk' : 'https://vignette.wikia.nocookie.net/starwars/images/1/1d/Bossk.png',
'Lando Calrissian' : 'https://vignette.wikia.nocookie.net/starwars/images/8/8f/Lando_ROTJ.png',
'Lobot' : 'https://vignette.wikia.nocookie.net/starwars/images/9/96/SWE_Lobot.jpg',
'Ackbar' : 'https://vignette.wikia.nocookie.net/starwars/images/2/29/Admiral_Ackbar_RH.png',
'Mon Mothma' : 'https://vignette.wikia.nocookie.net/starwars/images/b/b7/MP-MonMothma.png',
'Arvel Crynyd' : 'https://vignette.wikia.nocookie.net/starwars/images/d/de/Arvel-crynyd.jpg',
'Wicket Systri Warrick' : 'https://vignette.wikia.nocookie.net/starwars/images/4/4f/Wicket_RotJ.png',
'Nien Nunb' : 'https://vignette.wikia.nocookie.net/starwars/images/1/14/Old_nien_nunb_-_profile.png',
'Qui-Gon Jinn' : 'https://vignette.wikia.nocookie.net/starwars/images/f/f6/Qui-Gon_Jinn_Headshot_TPM.jpg',
'Nute Gunray' : 'https://vignette.wikia.nocookie.net/starwars/images/f/fd/Nute_Gunray_SWE.png',
'Finis Valorum' : 'https://vignette.wikia.nocookie.net/starwars/images/5/51/ValorumPortrait-SWE.png',
'Padmé Amidala' : 'https://vignette.wikia.nocookie.net/starwars/images/b/b2/Padmegreenscrshot.jpg',
'Jar Jar Binks' : 'https://vignette.wikia.nocookie.net/starwars/images/d/d2/Jar_Jar_aotc.jpg',
'Roos Tarpals' : 'https://vignette.wikia.nocookie.net/starwars/images/c/ca/TarpalsHS.jpg',
'Rugor Nass' : 'https://vignette.wikia.nocookie.net/starwars/images/d/d8/Bossnass.jpg',
'Ric Olié' : 'https://vignette.wikia.nocookie.net/starwars/images/4/4c/RicOlieHS-SWE.png',
'Watto' : 'https://vignette.wikia.nocookie.net/starwars/images/e/eb/WattoHS.jpg',
'Sebulba' : 'https://vignette.wikia.nocookie.net/starwars/images/1/14/Sebulba_Headshot_Closeup.png',
'Quarsh Panaka' : 'https://vignette.wikia.nocookie.net/starwars/images/7/72/PanakaHS-TPM.png',
'Shmi Skywalker' : 'https://bit.ly/2BqAa1r',
'Darth Maul' : 'https://vignette.wikia.nocookie.net/starwars/images/5/50/Darth_Maul_profile.png',
'Bib Fortuna' : 'https://vignette.wikia.nocookie.net/starwars/images/3/33/BibFortunaHS-ROTJ.png',
'Ayla Secura' : 'https://vignette.wikia.nocookie.net/starwars/images/f/f9/Aayla.jpg',
'Ratts Tyerell' : 'https://vignette.wikia.nocookie.net/starwars/images/6/68/RattsHS.jpg',
'Dud Bolt' : 'https://vignette.wikia.nocookie.net/starwars/images/7/73/Dud_Bolt_Podracer_Cockpit.png',
'Gasgano' : 'https://vignette.wikia.nocookie.net/starwars/images/5/57/GasganoHS-SWE.jpg',
'Ben Quadinaros' : 'https://vignette.wikia.nocookie.net/starwars/images/7/7f/Cropped_Quadinaros.png',
'Mace Windu' : 'https://vignette.wikia.nocookie.net/starwars/images/5/58/Mace_ROTS.png',
'Ki-Adi-Mundi' : 'https://vignette.wikia.nocookie.net/starwars/images/9/9e/KiAdiMundi.jpg',
'Kit Fisto' : 'https://vignette.wikia.nocookie.net/starwars/images/4/4c/Kit_Fisto_Card_Trader.png',
'Eeth Koth' : 'https://vignette.wikia.nocookie.net/starwars/images/4/4e/EethKothCardTrader.png',
'Adi Gallia' : 'https://vignette.wikia.nocookie.net/starwars/images/b/ba/AdiGallia.jpg',
'Saesee Tiin' : 'https://vignette.wikia.nocookie.net/starwars/images/6/68/Saesee_Tiin_Card_Trader.jpg',
'Yarael Poof' : 'https://vignette.wikia.nocookie.net/starwars/images/6/66/Yarael_Poof_Canon.jpeg',
'Plo Koon' : 'https://vignette.wikia.nocookie.net/starwars/images/b/bf/PloKoonCardTrader.png',
'Mas Amedda' : 'https://vignette.wikia.nocookie.net/starwars/images/3/37/Mas_Amedda_SWCT.png',
'Gregar Typho' : 'https://vignette.wikia.nocookie.net/starwars/images/5/52/Gregar_Typho.jpg',
'Cordé' : 'https://vignette.wikia.nocookie.net/starwars/images/b/b6/Cord%C3%A9_-_SW_Card_Trader.png',
'Cliegg Lars' : 'https://vignette.wikia.nocookie.net/starwars/images/3/36/ClieggLarsHS-SWE.jpg',
'Poggle the Lesser' : 'https://vignette.wikia.nocookie.net/starwars/images/9/93/Poggle_the_lesser_-_sw_card_trader.png',
'Luminara Unduli' : 'https://vignette.wikia.nocookie.net/starwars/images/2/21/LuminaraHS-SWE_%28new%29.png',
'Barriss Offee' : 'https://vignette.wikia.nocookie.net/starwars/images/3/37/Barrisprofile2.jpg',
'Dormé' : 'https://vignette.wikia.nocookie.net/starwars/images/1/18/Dormesenate.jpg',
'Dooku' : 'https://vignette.wikia.nocookie.net/starwars/images/b/b8/Dooku_Headshot.jpg',
'Bail Prestor Organa' : 'https://vignette.wikia.nocookie.net/starwars/images/5/50/Bail_Organa_Mug.jpg',
'Jango Fett' : 'https://vignette.wikia.nocookie.net/starwars/images/5/56/JangoInfobox.png',
'Zam Wesell' : 'https://vignette.wikia.nocookie.net/starwars/images/7/7d/Clawdite.jpg',
'Dexter Jettster' : 'https://vignette.wikia.nocookie.net/starwars/images/6/6c/DexterHS-SWE.jpg',
'Lama Su' : 'https://vignette.wikia.nocookie.net/starwars/images/7/73/Lama_Su.jpg',
'Jocasta Nu' : 'https://vignette.wikia.nocookie.net/starwars/images/1/15/Jocasta_Nu_SWE.png',
'R4-P17' : 'https://vignette.wikia.nocookie.net/starwars/images/6/6b/R4-P17.jpg',
'Wat Tambor' : 'https://vignette.wikia.nocookie.net/starwars/images/a/a5/Wat_Tambor.png',
'San Hill' : 'https://vignette.wikia.nocookie.net/starwars/images/6/6f/SanHill_hs.jpg',
'Shaak Ti' : 'https://vignette.wikia.nocookie.net/starwars/images/2/20/Shaak_Ti_closeup-SWE.png',
'Grievous' : 'https://vignette.wikia.nocookie.net/starwars/images/d/de/Grievoushead.jpg',
'Tarfful' : 'https://vignette.wikia.nocookie.net/starwars/images/3/37/Tarfful_RotS.png',
'Raymus Antilles' : 'https://vignette.wikia.nocookie.net/starwars/images/8/80/Raymus_card_trader.png',
'Sly Moore' : 'https://vignette.wikia.nocookie.net/starwars/images/e/ec/SlyMooreIsWatchingYouPoop-OfficialPix.jpg',
'Tion Medon' : 'https://vignette.wikia.nocookie.net/starwars/images/4/43/Tion_Medon.jpg',
'Finn' : 'https://vignette.wikia.nocookie.net/starwars/images/a/af/Finn_TLJ_Collector%27s_Edition.png',
'Rey' : 'https://vignette.wikia.nocookie.net/starwars/images/f/f8/ReyTLJEntertainmentWeeklyNovember.png',
'Poe Dameron' : 'https://vignette.wikia.nocookie.net/starwars/images/7/79/Poe_Dameron_TLJ.png',
'BB8' : 'https://vignette.wikia.nocookie.net/starwars/images/6/68/BB8-Fathead.png',
'Captain Phasma' : 'https://vignette.wikia.nocookie.net/starwars/images/0/02/Phasma.png'};

export const VEHICLES = {
'Sand Crawler' : 'https://lumiere-a.akamaihd.net/v1/images/databank_sandcrawler_01_169_55acf6cb.jpeg?region=431%2C0%2C877%2C878',
'T-16 skyhopper' : 'https://vignette.wikia.nocookie.net/starwars/images/e/e1/Lukes_T-16_Skyhopper_TT.png/revision/latest?cb=20170520044701',
'X-34 landspeeder' : 'https://img-new.cgtrader.com/items/1869055/739c01282a/star-wars-x-34-landspeeder-3d-model-low-poly-max-obj-mtl-fbx.jpg',
'TIE/LN starfighter' : 'http://fractalsponge.net/gallery/Starfighters/TIE%20Fighter/tf13.jpg',
'Snowspeeder' : 'https://cdn.myminifactory.com/assets/object-assets/5bf01809d660d/images/720X720-snowspeeder2.jpg',
'TIE bomber' : 'http://www.galacticempiredatabank.com/TIEBomber.jpg',
'AT-AT' : 'https://bit.ly/2oZ8DBt',
'AT-ST' : 'https://s3.amazonaws.com/hobbyworks_images/images/products/470x470/444554_20170504_212832.png',
'Storm IV Twin-Pod cloud car' : 'https://i.pinimg.com/originals/62/e0/0d/62e00d1f888409ac4582f93389444042.jpg',
'Sail barge' : 'https://www.syfy.com/sites/syfy/files/styles/1200x680/public/Sailbarge-chron2.jpg',
'Bantha-II cargo skiff' : 'https://vignette.wikia.nocookie.net/starwars/images/c/cc/Bantha-II_Cargo_Skiff_BG.png/revision/latest?cb=20161023211218',
'TIE/IN interceptor' : 'https://vignette.wikia.nocookie.net/starwars/images/6/65/Tieinter2.jpg/revision/latest?cb=20060705184051',
'Imperial Speeder Bike' : 'https://vignette.wikia.nocookie.net/starwars/images/4/47/Speeder_Bike_DICE.png/revision/latest?cb=20171102044625',
'Vulture Droid' : 'https://i.redd.it/ccjlhvoo69p11.jpg',
'Multi-Troop Transport' : 'https://vignette.wikia.nocookie.net/starwars/images/8/80/MTT-SWE.jpg/revision/latest?cb=20120206202352',
'Armored Assault Tank' : 'https://cdna.artstation.com/p/assets/images/images/014/146/168/large/vincenzo-crosswhite-screen11.jpg?1542681698',
'Single Trooper Aerial Platform' : 'http://www.modelermagic.com/wordpress/wp-content/uploads/2013/01/stap01-481x500-1.jpg',
'C-9979 landing craft' : 'https://i.ytimg.com/vi/79CFPTaicxU/maxresdefault.jpg',
'Tribubble bongo' : 'https://vignette.wikia.nocookie.net/starwars/images/d/d8/Bongo.jpg/revision/latest?cb=20080430201913',
'Sith speeder' : 'https://i.ebayimg.com/images/g/puAAAOSwFM1Zcqvi/s-l300.jpg',
'Zephyr-G swoop bike' : 'https://i.pinimg.com/originals/11/7a/85/117a85a70baece19ddc203063bf4e176.jpg',
'Koro-2 Exodrive airspeeder' : 'https://i.pinimg.com/originals/93/48/b0/9348b0d7eeadaaa0681869586f988298.jpg',
'XJ-6 airspeeder' : 'https://vignette.wikia.nocookie.net/starwars/images/2/25/Hotrod-NEGVV.jpg/revision/latest?cb=20110701074846',
'LAAT/i' : 'https://vignette.wikia.nocookie.net/starwars/images/6/6f/Lluckylekku.JPG/revision/latest?cb=20090310162541',
'LAAT/c' : 'https://vignette.wikia.nocookie.net/starwars/images/9/90/LAATc_TCW.jpg/revision/latest?cb=20080719010603',
'Tsmeu-6 personal wheel bike' : 'https://vignette.wikia.nocookie.net/starwars/images/2/2c/GrievWheelBike_wsmi.jpg/revision/latest?cb=20071215145011',
'Emergency Firespeeder' : 'https://vignette.wikia.nocookie.net/starwars/images/6/66/Fire_ship.jpg/revision/latest?cb=20051220124720',
'Droid tri-fighter' : 'https://images-na.ssl-images-amazon.com/images/I/51g6gR%2BYMwL.jpg',
'Oevvaor jet catamaran' : 'https://vignette.wikia.nocookie.net/starwars/images/6/60/Wookieeflyingcat.jpg/revision/latest?cb=20150919124829',
'Raddaugh Gnasp fluttercraft' : 'https://vignette.wikia.nocookie.net/starwars/images/4/40/WookieeFluttercraft-SWDB.jpg/revision/latest?cb=20080425140709',
'Clone turbo tank' : 'https://www.gosale.com/product_images/4982000/star-wars-clone-wars-turbo-4982200.jpg',
'Corporate Alliance tank droid' : 'https://http2.mlstatic.com/star-wars-corporate-alliance-tank-droid-jorge-trens-D_NQ_NP_14305-MLB20085758816_042014-F.jpg',
'Droid gunship' : 'https://vignette.wikia.nocookie.net/starwars/images/6/6d/DroidGunship-DB.png/revision/latest?cb=20141227052202',
'AT-RT' : 'https://images-na.ssl-images-amazon.com/images/I/71WE-ukXWyL._SL1500_.jpg',
'AT-TE' : 'https://lumiere-a.akamaihd.net/v1/images/databank_attewalker_01_169_4292c02c.jpeg?region=195%2C0%2C1171%2C878&width=960',
'SPHA' : 'https://vignette.wikia.nocookie.net/starwars/images/2/2a/SPHA-T.JPG/revision/latest?cb=20060515020703',
'Flitknot speeder' : 'https://bit.ly/32zphpZ',
'Neimoidian shuttle' : 'https://i.pinimg.com/originals/5a/97/54/5a975415b88c5faf9c28586877b7bcdf.jpg',
'Geonosian starfighter' : 'https://vignette.wikia.nocookie.net/starwars/images/8/82/Nantex-class_fighters.png/revision/latest?cb=20160117183706'};

export const STARSHIPS = {
'Executor' : 'https://vignette.wikia.nocookie.net/starwars/images/3/30/Executor_BF2.png/revision/latest?cb=20180903230846',
'Sentinel-class landing craft' : 'http://www.galacticempiredatabank.com/SentinelShuttle1.jpg',
'Death Star' : 'https://bit.ly/2P6xmi2',
'Millennium Falcon' : 'https://www.renderhub.com/squir/star-wars-millennium-falcon/star-wars-millennium-falcon-01.jpg',
'Y-wing' : 'https://lumiere-a.akamaihd.net/v1/images/Y-Wing-Fighter_0e78c9ae.jpeg?region=0%2C0%2C1536%2C864&width=960',
'X-wing' : 'https://static.turbosquid.com/Preview/2015/10/14__02_29_23/xwingtopleft_01_open_01.jpgb5dc9c7c-25bc-44f8-88ba-50e41873111aOriginal.jpg',
'TIE Advanced x1' : 'https://i.ytimg.com/vi/eBN8H2BHFO0/maxresdefault.jpg',
'Slave 1' : 'https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/boba-fett-ship-slave-1-aswego-arts.jpg',
'Imperial shuttle' : 'https://i.ebayimg.com/images/g/HugAAOSwIC1Zvfgj/s-l640.jpg',
'EF76 Nebulon-B escort frigate' : 'https://vignette.wikia.nocookie.net/starwars/images/5/50/NBfrigate.JPG/revision/latest?cb=20061215024715',
'Calamari Cruiser' : 'http://www.starwars-tw.com/story/vehicles/rebel/mon-calamari-cruiser-1.jpg',
'A-wing' : 'https://vignette.wikia.nocookie.net/starwars/images/1/13/RZ1-BF2.png/revision/latest?cb=20171005230121',
'B-wing' : 'https://live.staticflickr.com/4555/38550895996_f39e00a148_b.jpg',
'Republic Cruiser' : 'https://vignette.wikia.nocookie.net/starwars-exodus/images/3/3b/Republic_Cruiser.jpg/revision/latest?cb=20110512214018',
'Naboo fighter' : 'https://lumiere-a.akamaihd.net/v1/images/databank_naboon1starfighter_01_169_26691adf.jpeg?region=0%2C0%2C1560%2C878&width=960',
'Naboo Royal Starship' : 'https://vignette.wikia.nocookie.net/starwars/images/9/9e/Naboo_Royal_Starship.png/revision/latest?cb=20161019065403',
'Scimitar' : 'https://i.pinimg.com/originals/53/5e/fd/535efdfda410408873d0854a0030d12e.jpg',
'J-type diplomatic barge' : 'https://i.pinimg.com/originals/fd/e6/1c/fde61ccbd4c192e9c002526be40c5382.jpg',
'AA-9 Coruscant freighter' : 'https://lumiere-a.akamaihd.net/v1/images/aa-9-coruscant-freighter_a856053d.jpeg?region=92%2C0%2C1181%2C665&width=960',
'Jedi starfighter' : 'https://images-na.ssl-images-amazon.com/images/I/61ciWYi4UyL._SX679_.jpg',
'H-type Nubian yacht' : 'https://vignette.wikia.nocookie.net/starwars/images/f/fb/Nabooyacht.jpg/revision/latest?cb=20071216070919',
'Star Destroyer' : 'https://www.revell.de/out/pictures/master/product/1/03609_si_imperial_star_destroyer.jpg',
'Trade Federation cruiser' : 'https://i.pinimg.com/originals/2f/a1/2d/2fa12d607af47a04bd538a8182133630.jpg',
'Theta-class T-2c shuttle' : 'https://vignette.wikia.nocookie.net/starwars/images/8/8e/Theta-class_shuttle.png/revision/latest?cb=20180412042447',
'T-70 X-wing fighter' : 'https://spikeybits.com/wp-content/uploads/2018/10/Screenshot_334-1.jpg',
'Rebel transport' : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnRb1649tqFKltpF1f7N8Vafi-aEKE3n5nEXTfsdrk7xmUBvMb',
'Droid control ship' : 'https://bit.ly/32yfkcr',
'Republic Assault ship' : 'https://vignette.wikia.nocookie.net/starwars/images/2/2a/Acclamator_OCF.jpg/revision/latest?cb=20091003023542',
'Solar Sailer' : 'https://lumiere-a.akamaihd.net/v1/images/databank_geonosiansolarsailer_01_169_b3873578.jpeg?region=0%2C0%2C1560%2C878&width=960',
'Republic attack cruiser' : 'https://vignette.wikia.nocookie.net/starwars/images/0/0d/Imperial_attack_cruisers.png/revision/latest?cb=20140317112248',
'Naboo star skiff' : 'https://i.ebayimg.com/images/g/rBQAAOxyW1NREO~l/s-l300.jpg',
'Jedi Interceptor' : 'https://lumiere-a.akamaihd.net/v1/images/ETA-2-starfighter-main-image_bedd3aaa.jpeg?region=232%2C0%2C1451%2C816&width=960',
'arc-170' : 'https://images-na.ssl-images-amazon.com/images/I/71FALDRtlsL._SL1500_.jpg',
'Belbullab-22 starfighter' : 'https://vignette.wikia.nocookie.net/thelastofthedroids/images/4/48/Trench%27s_Belbullab-22.jpg/revision/latest?cb=20150125152927',
'V-wing' : 'https://vignette.wikia.nocookie.net/starwars/images/a/a9/V-wing_BF2.png/revision/latest?cb=20170825000555',
'CR90 corvette' : 'https://vignette.wikia.nocookie.net/es.starwars/images/0/0a/Corvette_negvv.jpg/revision/latest?cb=20081218232212',
'Banking clan frigate' : 'https://vignette.wikia.nocookie.net/starwars/images/0/07/Munificent_TCW.jpg/revision/latest/scale-to-width-down/2000?cb=20090311013715'};